# This is a basic workflow to help you get started with Actions

name: Build Zygisk Module

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up NDK using local-cache
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23

      # Install dependencies
#      - name: Install dependencies
#        run: sudo apt-get update && sudo apt-get install -y libncurses5

      # Step 4: Configure and Build with CMake
      - name: Build with CMake
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=android-31 \
                -S module/jni/libcxx \
                -B .
          cmake --build .

      # Upload the resulting artifact
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: libhookso
          compression-level: 9
          path: |
            x32/libs
            x64/libs